name: 'Import RAM Usage Check'
description: 'Check the amount of RAM used by a CircuitPython library import'
author: 'Alec Delaney'
inputs:
  firmware:
    description: 'A UF2 firmware file to load'
    required: true
  filesystem:
    description: 'A FAT12 filesystem to use (if given)'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
